#!/bin/bash

clear

# check https://github.com/microsoft/onnxruntime/releases
ONNXRUNTIME_VERSION="1.22.0" # change accordingly
ONNXRUNTIME_NAME="onnxruntime-linux-x64-$ONNXRUNTIME_VERSION" # change accordingly
ONNXRUNTIME_DIR="$(pwd)/$ONNXRUNTIME_NAME"
echo "onnx version: $ONNXRUNTIME_VERSION"
echo "onnx full version name: $ONNXRUNTIME_NAME"
echo "onnx full path: $ONNXRUNTIME_DIR"
echo "---------------------------------------------------------------------------------"

export ONNX_NET_FORWARD_DIR="$(pwd)/onnx_net_forward" # output directory 
echo "onnx_net_forward directory: $ONNX_NET_FORWARD_DIR"
rm -rf $ONNX_NET_FORWARD_DIR && mkdir $ONNX_NET_FORWARD_DIR

# download onnxruntime 
if [ ! -d "$(pwd)/onnxruntime-linux-x64-1.22.0" ]; then
    wget "https://github.com/microsoft/onnxruntime/releases/download/v$ONNXRUNTIME_VERSION/$ONNXRUNTIME_NAME.tgz"
    tar -xzf "$ONNXRUNTIME_NAME.tgz"
    rm "$ONNXRUNTIME_NAME.tgz"
    echo "onnxruntime downloaded and extracted."
    echo "---------------------------------------------------------------------------------"
fi

# compile the C++ code
echo "Compiling..."
rm -rf build && mkdir build && cd build
cmake .. \
    -DONNXRUNTIME_DIR="$ONNXRUNTIME_DIR" \
    -DONNXRUNTIME_INCLUDE_DIRS="$ONNXRUNTIME_DIR/include" \
    -DONNX_NET_FORWARD_DIR="$ONNX_NET_FORWARD_DIR" 
make
cd ..
rm -rf build
echo "Compilation completed."

# # create the .net file with python
# echo "Creating the .net file with python..."
# echo "----- Python --------------------------------------------------------------------"
# python create_net.py
# # python prepare_onnx_net.py
# echo "---------------------------------------------------------------------------------"

# copy the net.onnx file generated by python training into the onnx_net_forward directory
ONNX_NET_PATH="$(pwd)/data/best/net.onnx" # <- change accordingly
if [ ! -f "$ONNX_NET_PATH" ]; then
    echo "Error: net.onnx file not found at $ONNX_NET_PATH"
    exit 1
fi
cp "$ONNX_NET_PATH" "$ONNX_NET_FORWARD_DIR/net.onnx"
echo "$ONNX_NET_PATH copied to $ONNX_NET_FORWARD_DIR/net.onnx"

# test in MATLAB 
echo "----- Matlab --------------------------------------------------------------------"
matlab -nodisplay -nosplash -nodesktop -r "run('forward_test.m'); exit;"
echo "---------------------------------------------------------------------------------"
echo "MATLAB version test completed."


